services:
  # 1. Base de Datos Privada (MariaDB)
  - type: pserv
    name: imperio-mariadb
    env: image
    image:
      image: docker.io/bitnami/mariadb:latest
    plan: starter
    disk:
      name: mariadb-data
      mountPath: /bitnami/mariadb
      sizeGB: 1
    envVars:
      - key: MARIADB_ROOT_PASSWORD
        generateValue: true
      - key: MARIADB_DATABASE
        value: prestashop
      - key: MARIADB_USER
        value: prestashop
      - key: MARIADB_PASSWORD
        generateValue: true

  # 2. Tienda PrestaShop
  - type: web
    name: prestashop-app
    env: image
    plan: starter
    image:
      image: docker.io/bitnami/prestashop:latest
    # Persistencia para imágenes, módulos y configuraciones subidas
    disk:
      name: prestashop-data
      mountPath: /bitnami/prestashop
      sizeGB: 5
    envVars:
      - key: PRESTASHOP_HOST
        value: prestashop-app.onrender.com
      - key: MARIADB_HOST
        value: imperio-mariadb
      - key: MARIADB_PORT_NUMBER
        value: "3306"
      - key: MARIADB_DATABASE
        value: prestashop
      - key: MARIADB_USER
        value: prestashop
      - key: MARIADB_PASSWORD
        fromService:
          type: pserv
          name: imperio-mariadb
          envVarKey: MARIADB_PASSWORD
      - key: PRESTASHOP_FIRST_NAME
        value: Imperio
      - key: PRESTASHOP_LAST_NAME
        value: Admin
      - key: PRESTASHOP_EMAIL
        value: admin@imperio.ai
      - key: PRESTASHOP_PASSWORD
        generateValue: true
